name: dbutils_batch_query
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*
  - pip
  - pip:
    - ipython~=9.0.2
    - Jinja2~=3.1.6
    - json_repair~=0.40.0
    - openai~=1.69.0
    - pandas~=2.2.3
    - pytest~=8.3.5
    - python-dotenv~=1.1.0
    - toml~=0.10.2
    - tomlkit~=0.13.2
    - tqdm~=4.66.4