name: dbutils_batch_query
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pip
  - pip:
    - aiolimiter~=1.2
    - databricks-sdk~=0.50
    - ipython~=9.0
    - Jinja2~=3.1
    - json_repair~=0.40
    - openai~=1.69
    - pandas~=2.2
    - pytest~=8.3
    - python-dotenv~=1.1
    - tomlkit~=0.13
    - tqdm~=4.66